language: java

sudo: required

services:
  - docker
  - mysql

jdk:
  - oraclejdk8

before_install:
  - docker run -d --shm-size=1g -p 1521:1521 -p 8080:8080 alexeiled/docker-oracle-xe-11g
  - docker run -d -p 4369:4369 -p 5671:5671 -p 5672:5672 rabbitmq
  - docker run -d -p 27017:27017 mongo
  - docker ps
  - mysql -e 'CREATE DATABASE axon;'

install: true

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean verify -B
