services:
  axonserver:
    container_name: axonserver-springboot
    image: axoniq/axonserver:2025.2.0
    hostname: axonserver
    ports:
      - 8024
      - 8124
    environment:
      AXONIQ_AXONSERVER_STANDALONE_DCB: true
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
