services:
  axon-server:
    image: docker.axoniq.io/axoniq/axonserver:2025.2.0
    container_name: axon-framework-examples-axon-server
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      axoniq.axonserver.standalone-dcb: true
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_devmode_enabled: true
    volumes:
      - data:/axonserver/data
      - events:/axonserver/events

volumes:
  db:
    driver: local
  data:
    driver: local
  events:
    driver: local
