spring:
  application:
    name: springboot4-example
  docker:
    compose:
      enabled: true
      file:
        - file:examples/docker-compose.yaml

axon:
  axonserver:
    enabled: true
    # Be a bit more tolerant while Axon Server comes up
    connection-timeout: 5000
    reconnect-initial: 500
    reconnect-interval: 2000
  serializer:
    general: jackson
    events: jackson
    messages: jackson
