name: Dependabot Automation
on: pull_request

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot-approve:
        name: Dependabot PR Automation

        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Retrieve Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - name: Approve Pull Request
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#    dependabot-auto-merge:
#        runs-on: ubuntu-latest
#        if: ${{ github.actor == 'dependabot[bot]' }}
#        steps:
#            - name: Retrieve Dependabot metadata
#              id: metadata
#              uses: dependabot/fetch-metadata@v2
#              with:
#                  github-token: "${{ secrets.GITHUB_TOKEN }}"
#
#            - name: Auto-merge Pull Request
#              if: ${{steps.metadata.outputs.update-type != 'version-update:semver-major'}}
#              run: gh pr merge --auto --merge "$PR_URL"
#              env:
#                  PR_URL: ${{github.event.pull_request.html_url}}
#                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}