name: Announce release on Discuss

env:
  CA_FILE: /tmp/ca.pem
  URL: https://discuss.axoniq.io/posts.json

  # id of `Announcements` category in Discuss
  CATEGORY: 6

on:
  # Triggers the workflow on new release
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
      release_notes_file:
        required: true
        type: string
      release_date:
        type: number
        required: true

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:

      - name: Get authorities certificates
        run: openssl s_client -showcerts -connect discuss.axoniq.io:443 </dev/null | sed -n -e '/-.BEGIN/,/-.END/ p' > $CA_FILE

      - name: Read release notes file
        id: read_release_notes
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ inputs.release_notes_file }}

      - name: Create Discuss topic
        run: |
          
          echo $json | curl --cacert $CA_FILE -X POST "$URL" \
          -H "Api-Key: ${{ secrets.DISCUSS_KEY }}" \
          -H "Api-Username: axonbot" \
          -H 'Content-Type: application/json' \
          --data-binary @- << EOF
          {
            "title": "${{ release_name }}",
            "raw": "I’m glad to announce that we’ve released ${{ release_name }} on ${{ release_date }}.<br\>
          This release contains: <br/> ${{ release_notes}}",
            "category": $CATEGORY,
            "tags": ["release"]
          }
          EOF
        with:
          release_name: ${{ inputs.release_name }}
          release_date: ${{ inputs.release_date }}
          release_notes: ${{ steps.read_release_notes.outputs.content }}